# This determines the command prefix when there are conflicts (/name:home, /name:help, etc.)
name: RainBowCreationAPI
main: net.rainbowcreation.api.API
# Note to developers: This next line cannot change, or the automatic versioning system will break.
version: ${full.version}
website: https://rainbowcreation.net/
description: RainBowCreationCore.
authors: [RainBowCreation, NathanielSong, VocanicZ]
depend: [Essentials]
api-version: 1.13
permissions:
  rainbowcreation.verified:
    default: false