# This determines the command prefix when there are conflicts (/name:home, /name:help, etc.)
name: RainBowCreationCore
main: net.rainbowcreation.core.Core
# Note to developers: This next line cannot change, or the automatic versioning system will break.
version: ${full.version}
website: https://rainbowcreation.net/
description: RainBowCreationCore
authors: [RainBowCreation, NathanielSong, VocanicZ]
depend: [RainBowCreationAPI]
api-version: 1.13
permissions:
  rainbowcreation.verified:
    default: false