#####################################################################################
#  _____       _       ____                 _____                _   _              #
# |  __ \     (_)     |  _ \               / ____|              | | (_)             #
# | |__) |__ _ _ _ __ | |_) | _____      _| |     _ __ ___  __ _| |_ _  ___  _ __   #
# |  _  // _` | | '_ \|  _ < / _ \ \ /\ / / |    | '__/ _ \/ _` | __| |/ _ \| '_ \  #
# | | \ \ (_| | | | | | |_) | (_) \ V  V /| |____| | |  __/ (_| | |_| | (_) | | | | #
# |_|  \_\__,_|_|_| |_|____/ \___/ \_/\_/  \_____|_|  \___|\__,_|\__|_|\___/|_| |_| #
#                                                                                   #
############################################################################Core#####
#RainBowCreation.core by NathanielSong, VocanicZ
#Official Website: rainbowcreation.net
#LEGACY

# Database settings for MySQL
database:
  host: "127.0.0.1"
  port: 3306
  name: "minecraft"
  user: "root"
  password: "password"