jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - uses: gmitch215/TestMC@v2
        with:
          # Runs Latest Version
          path: '../../Target/RainBowCreation.jar'
          runtime: 'paper'
          time: 120
          commands: |
            rbc
  test-all:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        runtime: ['craftbukkit', 'spigot', 'paper']
        version: ['1.20.1', '1.20.2', '1.20.4', '1.20.6']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: gmitch215/TestMC@v2
        with:
          path: '../../Target/RainBowCreation.jar'
          runtime: ${{ matrix.runtime }}
          version: ${{ matrix.version }}
          time: 120
          commands: |
            rbc